### PR TITLE
update to Scala 2.12 and sbt 1.1

### LINKED ISSUE #14: a Scala 2.12 version would be good

### PR DESCRIPTION
**Pull request by bpholt**
This should cross-publish for Scala 2.11 and 2.12, but only with sbt 1. Hopefully losing sbt 0.13 support is acceptable.

This would fix #14 and supersedes #12.

### CODE REVIEW

**Comment by bpholt** [comment]
I'm not sure why the build is failing on TravisCI; running `admin/build.sh` works locally for me.

> `The command "openssl aes-256-cbc -K $encrypted_950849751342_key -iv $encrypted_950849751342_iv -in secrets.tar.enc -out secrets.tar -d" failed and exited with 1 during .`

I suspect @szeiger will need to investigate why that's failing.

**Comment by easel** [comment]
I was able to get this to build locally with 'plugin/publishLocal', it would be great to get something sbt 1.0 compatible published. I made an attempt at getting a cross-build to work but so far no luck.

**Comment by caente** [comment]
> I made an attempt at getting a cross-build

why not just have a new version of ornate that only works with sbt 1?

**Comment by bpholt** [comment]
> why not just have a new version of ornate that only works with sbt 1?

@caente unless I'm misunderstanding you, that's what this PR does.

**Comment by caente** [comment]
perhaps I misunderstood you, I thought the issue holding this PR back was the failure to cross compile, I suggested to *not* support 2.11 in the new version

**Comment by easel** [comment]
I think you're both correct -- this PR is sbt 1.0 only and does appear to work. It may or may not actually be held back by that, the repo owner hasn't weighed in on it.

**Comment by szeiger** [comment]
Hm, maybe just a bug in the script? PR builds from 3rd parties don't get the key for decrypting secrets. I'm looking into it.

**Comment by szeiger** [comment]
I thought I had done this before and it's really just standard Travis file encryption. I expected the build to continue without decrypting the secrets when the key is not set. I'll hack around it and rebase the PR.

**Comment by szeiger** [comment]
OK, that worked, but there's another build error. It can't find the sbt plugin for testing.

**Comment by szeiger** [comment]
Ah, it fails because it now tries to resolve the 2.12 version of Ornate for the `scripted` tests but they haven't been published yet at that point. The easiest way to fix this is to drop 2.11 support.

**Comment by szeiger** [comment]
Looks good. Thanks for opening this @bpholt

**Pull request merged**
